### ISSUE TITLE
Horizontal swipe to switch article is driving me nuts

### ISSUE THREAD

**Issue by Sebastian-dm** [FredJul/Flym#586] opened 2020-05-09 11:30 UTC
First of all, love the app. Thanks for a great product!

On almost every article that I read, I accidentally swipe a little bit left or right when I scroll down making the app go to the next article. this is very annoying since when I go back to the article I am reading it will be reset to the top so I have to find my place again. Plus it will also mark the next article as read.

I really hope the sensitivity can be lowered for the horizontal swipe article switch or make it toggleable in the settings.

Thank you in advance.

**Comment by Friptick** [comment] 2020-05-17 08:44
@Sebastiandmeier This seems to be identical to #480. Check before opening a new issue, otherwise dev will get annoyed and not fix anything! :)

**Comment by Sebastiandmeier** [comment] 2020-05-17 16:24
will do :)

**Comment by Friptick** [comment] 2020-05-23 06:23
Okay, @Sebastian-dm does not seem to want to close this issue, which duplicates #480.

So let's make it the issue original. Here is _another_ way swipe-switching may drive users nuts. To reproduce:

1. Scroll to bottom of an article, in order to read it all. Viewport is now positioned at bottom of article.
2. Swipe the article left to go to next article, i.e. to the right.
3. Boom: current article bounces back from the left into position, and only then, a split-second later, switches to the next article. Very disorienting UX.
4. But there's worse! The new article is now displayed, but the viewport is at the bottom! User needs to scroll up to top manually! Every time.

@FredJul : maybe you can pull the code for horizontal swiping from SpaRSS? That app is abandonware but its horizontal swiping does not have these issues and is beautifully smooth.

Thanks for your work, and for consideration.

**Comment by FredJul** [comment] 2020-05-24 22:05
@Friptick I actually wrote the SpaRSS slide mechanism since it is based on Flym v1. For Flym v2 I decided to do something much simpler (both to code and maintain) and more memory efficient, I'm sorry it does not suit you. However @mitsnosrap kindly developed an option to deactivate the swipe, so I hope it will be good enough for you.

**Closed by FredJul** 2020-05-24 22:05 UTC

**Comment by Friptick** [comment] 2020-05-25 05:07
@FredJul I guarantee that the swipe would not suit you either if you could see it! The problem is detailed in my explanation. Perhaps this is a problem affecting some devices only. Anyway, please do not take this as a criticism, I know that you work for free and appreciate it very much. Thanks.
