### ISSUE TITLE
Auto mark as read when scrolling

### ISSUE THREAD

**Issue by Donkey-Doug** [FredJul/Flym#740] opened 2021-01-06 23:29 UTC
Make it possible to mark an article as read when the user scrolls past it.

If the users scrolls down and an article disappears at the top op the display, mark it as read. This means that, in the unread section, the user cannot scroll back up, because articles that have been scrolled past are marked as read automatically.

**Comment by nikhilCad** [comment] 2021-01-07 15:16
Duplicate of #348

**Closed** 2021-01-07 19:31 UTC
